### ISSUE TITLE
stackoverflow insted of no method error

### ISSUE THREAD

**Issue by pfitzseb** [JunoLab/CodeTools.jl#10]
when doing something like 

``` julia
using CodeTools
include_string(Main, "sin()")
# or even
include_string("sin()") # which I don't understand at all, because this should only call a Base method
```

This may be a bug with `Lazy.jl` since the error pretty much occurs there, but this should definitely throw a 

```
ERROR: LoadError: MethodError: `sin` has no method matching sin()
```

instead of trying to print a `Lazy.List`.

**Comment by MikeInnes** [comment]
I can reproduce this with

``` julia
using Lazy
sin()
```

If you run `e = try sin() catch e e end;` you'll see that `sin()` actually ends up _throwing_ an infinitely nested List object (!) instead of whatever error it was supposed to produce.

My hunch is that Lazy.jl has ended up overloading one of the new methods that 0.4 introduced, and that this has thrown things off somewhere in the method-error-handling stack.
