### ISSUE TITLE
Fix includeline to follow e.g. `joinpath`

### ISSUE THREAD

**Issue by pfitzseb** [JunoLab/CodeTools.jl#27]
Throwing a simple `eval(parse(...))` in at
https://github.com/JunoLab/CodeTools.jl/blob/67acafc4e8668df18c869fb676a3ade66b3e8c51/src/module.jl#L129
will work for simple cases (static `joinpath`, e.g. `include(joinpath("foo", "bar.jl"))`), but is iffy.

cc: @Datseris

**Comment by MikeInnes** [comment]
I'm not clear on why people use that idiom. Julia should just handle the path differences if you write `include("foo/bar.jl")`.

**Comment by Datseris** [comment]
@MikeInnes very simple why I would use that: Noone ever told me that the other syntax works.

Since on Windows I was using `path1\\path2\\...` and on linux i was using `path1/path2/...` I did not imagine that the second syntax would work on Windows as well. Since this is not mentioned anywhere in the Julia docs I just remained ignorant and used `joinpath` so I dont have to write stuff 2 times in windows and linux.

If this truth that `foo/bar` works on any machine is somewhere in the docs please let me know so I can see that! Because whenpfitzeb told me that it works anywhere, I was completely mindblown!

**Comment by MikeInnes** [comment]
Not sure if it's documented officially, but it's how Base Julia and most packages (including the whole Juno stack) are written, so if it was likely to cause problems you probably would have seen them already :)

Will close this for now as it's easiest to support the one syntax as standard.
